# Use this to define local configurations for your project.
# Any configuration defined here will override its global counterpart.
# Global configurations are located in `C:\Users\giovi\AppData\Roaming\YGOFabrica\config.toml`.
locale = 'en'
[expansion.pioxii]
default = true
recipe = ['pioxii.toml']
[gamedir.main]
path = 'c:\ProjectIgnis'
default = true