[[card]]
id = 600000000
name = "Davide"
type = "monster"
level = 3
atk = 800
def = 1200
flavor-text = '''
Parente stretto del gorilla. Questo animale è solito avventurarsi in
ambienti sociali disagiati.
Non è particolarmente offensivo, né intelligente. ha una
particolare avversione per le banane e per le fragole.
'''
race = "beast-warrior"